### ISSUE TITLE
Differentiate Environments at one glance

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#10]
We have serveral "types" of environments:
1- Prod: the production environment accessible at dashboard.unee-t.com
2- Main Dev: the Main DEV environment for the BZFE accessible at dev.dashboard.unee-t.com
3- Local DEV: an environment that a developer can create on a local machine (or on an dedicated AWS instance).
4- Demo Environment (does not exist yet) where we can showcase what unee-t does today with demo cases and demo users.
5- Test Environment (does not exist yet) where we can show and test the newest features that are about to be rolled out with demo cases and demo users.

We need to be able to differentiate these environment in one glance to avoid silly mistakes.

We will do that by creating different color scheme for each of these 5 types of environment.
This will be done by:
1- creating a slightly different version of the skin for each of the environment
2- assign this skin (initially manually in the BZ back end and then automatically as we deploy the environment) to the correct environment.

This issue track our progresses to achieve that.

**Comment by franck-boullier** [comment]
@kaihendry I have created a new branch for that and all seem to work as I intended to EXCEPT that when I want to change the version number of the [docker-compose.yml](https://github.com/unee-t/bugzilla-customisation/blob/master/docker-compose.yml) file the make down command throws an error:

> ubuntu@ip-172-31-21-141:~/bugzilla-customisation$ make down
docker-compose down
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Makefile:11: recipe for target 'down' failed
make: *** [down] Error 1

I'd like to keep proper version tracking.
Any idea how can I fix this? What am I doing wrong?

**Comment by kaihendry** [comment]
Track version in git, not inside the file. Version 2 is docker compose specific thing and it should not be changed.

**Comment by kaihendry** [comment]
We could `sed` change some CSS like we do for the version number from [.travis.yml](https://github.com/unee-t/bugzilla-customisation/blob/master/.travis.yml)

![version](https://user-images.githubusercontent.com/765871/34595542-d51df6a4-f213-11e7-8f64-3e1ae782cc59.png)

**Comment by franck-boullier** [comment]
@kaihendry That's probably a much better approach indeed!
