### ISSUE TITLE
Params for local installation are not correct

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#11]
in the folder https://github.com/unee-t/bugzilla-customisation/tree/differentiate_envo/params there are 2 params.json files:
- dev-params.json
- prod-params.json

1 is missing:
- local-params.json
This should set all the parameters that are needed for a local environment except the values that are specific to the local installation:
- urlbase
- maintainer
- email parameters

@kaihendry can you let me know what should be done so we can deploy a local installation with all the other parameters which are not installation dependent correctly configured?

**Comment by kaihendry** [comment]
For local dev I am just using something I quickly created and defined here: https://github.com/unee-t/bugzilla-customisation/blob/master/.env#L7

I don't think this really matters for local development. I will add it when I get a chance.

**Comment by franck-boullier** [comment]
"I don't think this really matters for local development."
It's not critical but is does matter are some important parameters need to be configured there so that the installation behaves as intended (permissions, group access, security, etc...) we can always set that up manually but this is an additional process that should ideally be automated so that all developers work with the same version of the environment.

**Comment by kaihendry** [comment]
Fixed in https://github.com/unee-t/bugzilla-customisation/commit/062175f6d9933b07e9cd3b8631b06f66da651879
