### ISSUE TITLE
Use a Bugzilla user instead of root when connecting to RDS

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#15]
Guide creating a user:
https://bugzilla.readthedocs.io/en/5.0/installing/mysql.html#mysql
```
GRANT SELECT, INSERT,
UPDATE, DELETE, INDEX, ALTER, CREATE, LOCK TABLES,
CREATE TEMPORARY TABLES, DROP, REFERENCES ON bugs.*
TO bugzilla@localhost IDENTIFIED BY '$DB_PASS';

FLUSH PRIVILEGES;
```

**Comment by kaihendry** [comment]
@franck-boullier  this `REFERENCES ON bugs.*`.. isn't that referring the user? In our case, 'bugzilla'?

**Comment by franck-boullier** [comment]
not sure where this is stored but I'll be surprised.
The DB user credentials for the BZ installation are stored in the localconfig file and nowhere else as far as I know it

**Comment by kaihendry** [comment]
Just confused about the meaning of `CREATE TEMPORARY TABLES, DROP, REFERENCES ON bugs.*` from https://bugzilla.readthedocs.io/en/5.0/installing/mysql.html#mysql

Isn't it referring to the user?

**Comment by kaihendry** [comment]
Ok, this obscure command does create a user. I checked with `SELECT User, Host, Password FROM mysql.user;`

    MariaDB [bugzilla]> GRANT SELECT, INSERT,
    -> UPDATE, DELETE, INDEX, ALTER, CREATE, LOCK TABLES,
    -> CREATE TEMPORARY TABLES, DROP, REFERENCES ON bugzilla.*
    -> TO bugzilla@% IDENTIFIED BY 'SECRET';


Needed the wildcard % which oddly isn't * otherwise I couldn't connect to it. Better to use security groups to limit access, not IP addresses imo.
