### ISSUE TITLE
parameters for local deployement are not working

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#16]
https://github.com/unee-t/bugzilla-customisation/commit/062175f6d9933b07e9cd3b8631b06f66da651879
This commit does not seem to work as intended: the parameters are NOT what is expected.

I've created a branch (https://github.com/unee-t/bugzilla-customisation/tree/db_configuration_for_bz) that tries to fix that also but the parameters are still not changed to what we need even after the
make down
make up
sequence in my "local/aws" machine...
@kaihendry any idea what might be wrong?

**Comment by kaihendry** [comment]
If you look at .env, the PARAMS_URL points to a httpd hosted params.

e.g.
PARAMS_URL=https://raw.githubusercontent.com/unee-t/bugzilla-customisation/master/params/local-params.json

on the master branch. I did it this way, to avoid having to inject a new file in the docker image and to keep flexible.

If you are expecting to see changes immediately reflected, that won't work until you commit. And be sure to point to your branch from .env!

e.g. https://raw.githubusercontent.com/unee-t/bugzilla-customisation/db_configuration_for_bz/params/local-params.json

**Comment by franck-boullier** [comment]
I understand the logic and I think it's sound.

What I did:
- created a new feature branch ( db_configuration_for_bz) and update the file /bugzilla-customisation/master/params/local-params.json so it reflects the correct parameter we need.
- pushed the branch
- on my dev machine 
  - make down
  - checkout and pulled the newly created branch with the correct paramaters for local environments.
  - make up
- go to the BZFE on my local/AWS machine

Expected result: the parameters are correct as defined in the file /bugzilla-customisation/master/params/local-params.json

Actual result: the environment is NOT using these parameters...

@kaihendry Any idea?

**Comment by kaihendry** [comment]
https://github.com/unee-t/bugzilla-customisation/blob/db_configuration_for_bz/.env#L7 is incorrect.

Change the variable to https://raw.githubusercontent.com/unee-t/bugzilla-customisation/db_configuration_for_bz/params/local-params.json

**Comment by franck-boullier** [comment]
Oooohhhh!!
OK got it!

**Comment by franck-boullier** [comment]
Nope...
Thought I got it but still no luck...
my .env file is now
<img width="777" alt="env_file" src="https://user-images.githubusercontent.com/31331637/33201649-68960c38-d134-11e7-9328-d09f4996d37e.PNG">

but still no luck: parameters are still not correct...

**Comment by kaihendry** [comment]
What variable do you test for and how do you do it?

**Comment by franck-boullier** [comment]
I go to the back end in my dev environment and see if the parameters are displayed as expected.
Example: the parameter 
"allowemailchange" : "0"
Should reflect in the back end as
allowemailchange: 'off'.

It is still defined as 'on'...

**Comment by kaihendry** [comment]
Is any other parameter reflected? like urlbase ?

**Comment by franck-boullier** [comment]
urlbase is not expected and not reflected either

**Comment by franck-boullier** [comment]
When recreating a new installation from scratch the local parameters are correctly reflected...
Closing it (event though no real understanding of why the make up/make down sequence does not work as expected...)
