### ISSUE TITLE
Query Performance issue

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#21]
After adding bug group and also attach_data the performances of Unee-T becomes agonizingly slow to the point where we are hitting timeout errors in the BZFE.

We need to address this.
One solution is to add more indexes in the database to speed up some key queries.

This issue tracks our progresses to remove that performance bottleneck and make sure perfs are acceptable with a large number of cases, users and unit.

**Comment by sebdeckers** [comment]
What is different from the deployment used at LMB?

**Comment by nbiton** [comment]
What kind of operations slow down after you add those things?

**Comment by franck-boullier** [comment]
@nbiton Slowed down operation: type a case number in the search box: it'll take about 20 to 30sec for the case to be displayed.
@sebdeckers The differences between deployment @LMB is that we use 
-groups, 
-group_control_map 
- group_group_map
-group_user_map
_bug_group_map
to restrict access to cases to certain users only.
We have also created a lot more flagtypes (6 flagtypes per product/unit) and the flaginclusions table is much bigger than before (it was empty).
These are the differences I can think of at this point...

**Comment by franck-boullier** [comment]
Test to replicate the issue:
go to dev.dashboard.unee-t.com
type a case number in the search box.
Time the duration for the case to be populated on the interface

**Comment by franck-boullier** [comment]
More information and case where the BZFE is broken:
in dev.dashboard.unee-t.com
Test:
- Create a new user in the BZFE (as admin)
- Try to log to the BZFE with this user credentials 

Result: 
504 Gateway Time-out

**Comment by franck-boullier** [comment]
@kaihendry any idea on what could cause that?

**Comment by franck-boullier** [comment]
First step in the right direction:
Adding a missing index to the table 'group_group_map' has cut the query time for a query specific to 1 user with a LOT of group membership from 87.4sec to 55.5 sec.
55 seconds is still very high though but this is a significant improvement...
BZFE database needs to be upgraded to v2.10 to benefit from this improvement.

**Comment by franck-boullier** [comment]
Issue is still present on the dev instance using RDS and load balancer.
@kaihendry 
This seems to be a know issue in AWS: https://aws.amazon.com/premiumsupport/knowledge-center/504-error-classic/
Need to investigate more

**Comment by franck-boullier** [comment]
I'll move the conversation about the infrastructure related issue to slack.
Let's keep this issue strictly about perf of the app and handle the infrastructure related issues separately.

**Comment by sebdeckers** [comment]
@byte Dealing with a crazy performance bottleneck due to *interesting* ~~ab~~use of Bugzilla's database. What profiling tools should we use for MySQL/MariaDB? Sorry for the noob question. 🔰🙇🏼‍♂️

**Comment by sebdeckers** [comment]
Pinging @majkelcc This is the thread about the DB issues I mentioned. Any tips?

**Comment by majkelcc** [comment]
Do we know if it's a problem with few slow queries, or a big number of them? I'd first catch all queries with their times for a single request.

> 1 user with a LOT of group membership

how much is a LOT? 😉 

@sebdeckers do I remember correctly and these groups-related tables something that was added on top of bugzilla?

**Comment by franck-boullier** [comment]
@majkelcc 'do I remember correctly and these groups-related tables something that was added on top of bugzilla?'
Actually no, we are using the vanilla system for group membership...
The difference is that we are probably stretching it above what the initial creator of BZ had in mind as we create about 30 groups for each BZ product/unit.
The consequence is that a user in charge of a lot of units will have to be a member of multiple groups.

It seems that the login logic for BZ requires that we pull all the groups a user belongs to when the user logs in for the first time. The time to get that information increase proportionnally with the number of groups that the user is a member of.

I'm going to create a script to generate many product/units and the correspondinf groups so we can simulate a configuration with as many products and group as we want to stress test the sytem...

**Comment by franck-boullier** [comment]
@majkelcc 'Do we know if it's a problem with few slow queries, or a big number of them'
As of today it seems that this is 1 slow running query as per the MariaDB slow_query_log...

**Comment by majkelcc** [comment]
@franck-boullier can you paste this query here?

**Comment by franck-boullier** [comment]
@majkelcc sorry for the late reply.
I'll post this query here but it will be impossible for you to replicate the issue unless we have several users, groups and units to test against

I'm working on a script to do that (mass insert of objects in the BZFE).
It should be ready soon...

**Comment by byte** [comment]
can you check what is reported in the slow query log? please paste output here. also, you want to see EXPLAIN of said query. if you are trying to see what MariaDB Server is doing, the EXPLAIN will help (and also see if you need to add an index).

**Comment by franck-boullier** [comment]
by popular demand...
[slow.log](https://github.com/unee-t/bugzilla-customisation/files/1534812/slow.log)
[slow_query_analysis.zip](https://github.com/unee-t/bugzilla-customisation/files/1534848/slow_query_analysis.zip)

**Comment by kaihendry** [comment]
mysqldump -h db.dev.unee-t.com -P 3306 -u root --password=$(aws --profile lmb-dev ssm get-parameters --names MYSQL_ROOT_PASSWORD --with-decryption --query Parameters[0].Value --output text) bugzilla  > dev.sql

The current dev.sql database of 17GB (uncompressed) can't be run in my [local mariaDB container](https://github.com/unee-t/bugzilla-customisation/blob/master/docker-compose.yml#L29).
https://s.natalian.org/2017-12-08/1512707082_2164x1398.png

Might be due to the regular 10GB limit of Docker containers: `docker storage-opt dm.basesize=10G`

I am going to assume attachments were stored in this database. Can we *PLEASE* split them out?

**Comment by franck-boullier** [comment]
"I am going to assume attachments were stored in this database"
That is right, attachments are stored in a dedicated table in the BZ Db.

When I did the import in the dev, I ran a separate import script which worked well.

"Can we PLEASE split them out?"
Not sure how we can do that and how this is related to the timeout issue and/or the Db performance issue...
Maybe we want to create a separate issue for that:
In any case, the decision has been made that we will have 2 types of attachments in Unee-T:
- Simple attachment are handled outside of BZ altogether and typically in S3 (@nbiton is currently working on that)
- Complex attachment that need flags and tags and comments are still handled in BZ until further notice.
Let's discuss this as a separate issue anyway...

**Comment by franck-boullier** [comment]
'The current dev.sql database of 17GB (uncompressed) can't be run in my local mariaDB container.'

For the record, I can run it without any issue in my local/AWS dev environment...

**Comment by franck-boullier** [comment]
@byte and @majkelcc 
There is now a [script](https://github.com/unee-t/bz-database/blob/master/demo-test%20environment/insert_DEMO-TEST_users_in_unee-t_bzfe_v2.11.sql) that creates users and units in bulk so we can stress test the application and simulate the issue in a dev environment.

Let me know how I can help and what ideas you might have to sort this one out.

Thanks!

**Comment by franck-boullier** [comment]
@byte and @majkelcc 
There is now a [script](https://github.com/unee-t/bz-database/blob/master/demo-test%20environment/insert_DEMO-TEST_users_in_unee-t_bzfe_v2.11.sql) that creates users and units in bulk so we can stress test the application and simulate the issue in a dev environment.

Let me know how I can help and what ideas you might have to sort this one out.

Thanks!

**Comment by majkelcc** [comment]
@franck-boullier this query is not that bad, but it produces over 10 million combinations matching the query. And from what I see it looks like the database tries to scan the index this many times. I created some sample data locally and was able to go from ~90 seconds to tens of milliseconds (!) by replacing the index.

Try this:

```sql
ALTER TABLE group_group_map DROP KEY group_group_map_member_id_idx;
CREATE INDEX `group_group_map_member_id_grant_type` ON group_group_map (`member_id`,`grant_type`);
CREATE INDEX `group_group_map_grantor_id_grant_type` ON group_group_map (`grantor_id`,`grant_type`);
```

I added two indexes in place of one to avoid potential issues in other queries.

**Comment by majkelcc** [comment]
> The current dev.sql database of 17GB (uncompressed) can't be run in my local mariaDB container.

If most of this size is taken by attachments maybe for dev purposes you could simply try to empty the column containing attachments? Everything should still work (besides viewing attachments of course).

**Comment by kaihendry** [comment]
@majkelcc Yeah, I figured out last week how to get rid of that table over here:
https://github.com/unee-t/bugzilla-customisation/issues/28#issue-280370594

**Comment by franck-boullier** [comment]
@majkelcc I like the performance boost, that's super impressive!

1 concern is that by dropping the key 'group_group_map_member_id_idx' we are also dropping the unique key (`member_id`,`grantor_id`,`grant_type`) for the table.

Is there a way to keep the same perf boost and also retain a unique key for the table?

**Comment by majkelcc** [comment]
@franck-boullier I'm afraid there's no way to keep both (not without changing the query itself), but depending on how the app is written it might not be needed at all (shouldn't be).

**Comment by franck-boullier** [comment]
@majkelcc I was afraid you were going to say that (not surprised though :-)) 
I agree with you that it should not be an issue, I can't think of a scenario where the app create the same group several times unless we run a poorly written script directly in the database...

I'll close this issue as we have a working solution for now.
Thanks a lot!

**Comment by kaihendry** [comment]
Has this schema/database suggestion/change been rolled out to production RDS?

**Comment by franck-boullier** [comment]
@kaihendry yes they have

**Comment by kaihendry** [comment]
Was this before or after the extremely slow response times around midday yesterday?

**Comment by franck-boullier** [comment]
before

**Comment by kaihendry** [comment]
Makes me think there is still some work to be done RE performance then.

**Comment by franck-boullier** [comment]
Yep! We'll create a dedicated issue once we have identified the culprit for this new problem.
On the plus side: we're learning new stuff and making the system better! Yay for Beta!

**Comment by kaihendry** [comment]
Can we continually log slow.log and make sure the DBA experts like @majkelcc have them to hand for analysis?

**Comment by franck-boullier** [comment]
yes, we should do that.
I will create user credential for the DBA so they can access the mysql database: this is where the slow_query_log are recorded for RDS

**Comment by kaihendry** [comment]
For dev, the RDS logs are now being streamed to Cloudwatch:
https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logStream:group=/aws/rds/instance/bugzilla/slowquery

Background info: https://aws.amazon.com/blogs/database/monitor-amazon-rds-for-mysql-and-mariadb-logs-with-amazon-cloudwatch/
