### ISSUE TITLE
BZ default configuration should use UTC

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#26]
To minimize the risk of time zone issue, the installation should use UTC as the default timezone.

In the BZ back-end, this is done as administrator by going to /editsettings.cgi and change the parameter 'Timezone used to display dates and times ' to UTC.

We need to alter the default parameters when we build Unee-T to reflect that.

**Comment by kaihendry** [comment]
Default timezone is UTC of a Bugzilla installation.

You can check like so: 

    curl -i https://dev.dashboard.unee-t.com/rest/timezone

or 

    curl -s https://dashboard.unee-t.com/rest/timezone
