### ISSUE TITLE
Application timeout issue due to slow DB queries

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#28]
BG: https://unee-t.slack.com/messages/C871N3LFP/convo/C871N3LFP-1512708819.000007/ & https://s.natalian.org/2017-12-08/504.png

    mysqldump -h db.dev.unee-t.com -P 3306 -u root --password=$(aws --profile lmb-dev ssm get-parameters --names MYSQL_ROOT_PASSWORD --with-decryption --query Parameters[0].Value --output text) --ignore-table=bugzilla.attach_data bugzilla  > dev.sql

is ~330M. Full DB with attachments is 17GB: https://github.com/unee-t/bugzilla-customisation/issues/21#issuecomment-350169675

Currently RDS configurations between dev and prod are different.

**Comment by kaihendry** [comment]
This query on login seems crazy slow: https://s.natalian.org/2017-12-08/1512709174_2164x1398.png

I'm debugging like so:

    innotop -h db.dev.unee-t.com -P 3306 -u root --password=$(aws --profile lmb-dev ssm get-parameters --names MYSQL_ROOT_PASSWORD --with-decryption --query Parameters[0].Value --output text)

**Comment by franck-boullier** [comment]
We know the query is slow: we are addressing this in issue #21 

This issue should be about the AWS timeout issue in the dev environment IMO so we can tackle these different (albeit related) problems separately.

My intuition is that fixing the timeout should MUCH faster than fixing the BZ query issue...

**Comment by kaihendry** [comment]
The application timeout is some arbitrary limit like a minute (at a guess). I'm confident we would not see the timeout if the query was fast. So I am not sure what you are asking me to do there. Somehow configure the timeout to >1min?

**Comment by franck-boullier** [comment]
"Somehow configure the timeout to >1min?"
Exactly
This is a temporary fix until we can sort out and fix the underlying issue with the query (see issue #21)

**Comment by kaihendry** [comment]
I bumped the Application load balancer timeout from 60s to 120s.

**Comment by kaihendry** [comment]
https://www.youtube.com/watch?v=BiScul_hGNg&feature=youtu.be video about enabling slow log on a RDS.

**Comment by franck-boullier** [comment]
If I'm not mistaken, slow_log is already enabled in the dev.
@kaihendry are you OK to close this issue now?

From my POV, the only thing we can do for now is:
1- Make sure that the timeout is the same in the prod too (so we can do private Beta despite issue #21.
2- Make sure that the DB expert find a way to improve the slow query (issue #21) that is causing this timeout issue in the first place.

**Comment by kaihendry** [comment]
I'm unable to reproduce the timeout on login, so perhaps you can close it.

**Comment by franck-boullier** [comment]
closing this:
- timeout increase and
- first DB optimization (see case #21) 
have made the problem disappear in the dev.

**Comment by kaihendry** [comment]
Dumping some resources I found in my travels:

* https://mariadb.com/kb/en/library/slow-query-log-overview/
* https://mariadb.com/kb/en/library/explain-in-the-slow-query-log/
* https://github.com/jynus/query-optimization
* https://metacpan.org/pod/DBI#DBI_TRACE
