### ISSUE TITLE
Implement PARAMS_URL

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#3]
Blocked by https://travis-ci.org/unee-t/bugzilla

@franck-boullier a params.json can be snagged after you've configured it via the Web interface like so: `docker cp customisation_bugzilla_1:/opt/bugzilla-5.0.3/data/params.json /tmp/params.json`

**Comment by kaihendry** [comment]
Done with https://github.com/unee-t/bugzilla-customisation/commit/68ab89122f79310c2e77df912482d7135e2b5941

**Comment by franck-boullier** [comment]
@kaihendry which instance shall I connect to to run this command?
How will this work with the load balanced configuration?

**Comment by kaihendry** [comment]
Load balanced configuration shouldn't be used since you don't know which of the instances in a cluster configuration have the correct settings.

If you want to further develop the params.json, I recommend doing it locally via https://github.com/unee-t/bugzilla-customisation/blob/master/.env

I'll commit the params.json and hopefully it will become clearer what the differences. Currently just **urlbase**.

**Comment by franck-boullier** [comment]
OK noted.
I'll update and commit the blob/master/.env file then
Ignore this...
I meant to say: I'll look at the params.json file that you'll commit and do the necessary tweaks...

**Comment by franck-boullier** [comment]
@kai, I'm trying to find the params.json file on my "local" install (ubuntu on AWS).
Based on your 1st comment I assumed that it would be located on /opt/bugzilla-5.0.3/data/params.json...
Unfortunately my /opt folder looks empty...
What is the full path to the params.json file on a local machine?
I need this so I can compare the working params.json that is currently on my dev envo to the vanilla one that you'll push later

![image](https://user-images.githubusercontent.com/31331637/32429189-7b5cec94-c304-11e7-9371-9593fea94bef.png)

**Comment by kaihendry** [comment]
On your Ubuntu host, you are running Docker containers. You should be able to see Bugzilla running with `docker ps`.

`docker cp customisation_bugzilla_1:/opt/bugzilla-5.0.3/data/params.json /tmp/params.json` is how to get the params.json from your Docker container to the host. I think you are looking at /opt on your host.

**Comment by franck-boullier** [comment]
OK thanks all clear for me now
