### ISSUE TITLE
Saved search queries do not work

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#33]
<img width="1680" alt="screen shot 2018-01-19 at 11 21 35 am" src="https://user-images.githubusercontent.com/765871/35133401-00728dc2-fd0b-11e7-8dcd-c1bb2bfa0f78.png">

I think it's saving the query as something unnecessarily complex.. 
workaround is to bookmark a simple search, e.g. https://dev.dashboard.unee-t.com/buglist.cgi?quicksearch=house&list_id=509068

**Comment by franck-boullier** [comment]
fixing issue #36 also fixed that issue
