### ISSUE TITLE
Timetracking information not accessible in prod anymore

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#34]
We have a weird issue in the prod environment:
Timetracking information are not accessible for users even though they are granted membership to the group that allow visibility and editing of the timetracking information.

This is true for user Nast or Franck for example.

It seems that the group membership is ignored by BZ.

A problem that might be related to that is that admin user are not able to impersonate another user in the LIVE anymore.

This problem does NOT happen in the dev/staging environment.

We need to understand what are the differences between both environments to pinpoint the root cause of the issue.

This documents our investigations.

**Comment by kaihendry** [comment]
What is time tracking? Do you have a URL or screenshot to make that a bit clearer to me?
Have you been tracking the changes in the database for this particular feature?

**Comment by franck-boullier** [comment]
root cause of the issue was a change in the group names.
This change (we replaced "_" with "-") had several consequences:
1- BZ considered that the bz system groups had been deleted and re-created these groups with '_' instead of '-' creating duplicates
2- The group preferences were reset in the BZ configuration as these are based on group names and not on group ids

Fix was:
1- Delete the groups that had been re-create automatically
2- Re-name the bz default groups and replace '-' with '_'
3- Re-configure the Group security in the BZ back end.

Test done:
- Admin user can now impersonate another user PASSED
- Timetracking information are visible for admin PASSED
- Deadline is visible for admin PASSED
- Impersonate 1 user and check if user can see timertracking and deadline PASSED
