### ISSUE TITLE
Deadline field is not visible on the newly created units

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#35]
We have one field 'Deadline' in the list of available fields for a case.
This field is part of the 'timetracking' family of fields and is made visible to user who are member of the timetracking group.

The issue:
In case 12345, the 'Deadline' field is visible for a user that is a member of the group 'syst_see_timetracking' (the time tracking group)
![deadline_field_visible](https://user-images.githubusercontent.com/31331637/35372556-9c25f56e-01d5-11e8-854d-f1adf537fcbb.png)

In case 61885, the  'Deadline' field is NOT visible for a user that is a member of the group 'syst_see_timetracking' (the time tracking group) 
![deadline_field_not_visible](https://user-images.githubusercontent.com/31331637/35372730-69eba804-01d6-11e8-8fc0-890dd5630145.png)

even though other time tracking information are visible on the case
![timetracking_information_visible](https://user-images.githubusercontent.com/31331637/35372659-1af2c020-01d6-11e8-9c7a-7b878d8e3d7d.png)

We need to understand why this happens so that the 'Deadline' field is available to users that are member of the group 'syst_see_timetracking' (the time tracking group) 

The only apparent difference between the 2 cases is that they are for different units...

@kaihendry do you want to have a crack at this one?

**Comment by kaihendry** [comment]
Am I able to reproduce this issue with the SQL here https://github.com/unee-t/bugzilla-customisation/tree/master/sql or here https://github.com/unee-t/bz-database ?

Or is my best tact for reproducing this issue is to dump the sql ?

**Comment by kaihendry** [comment]
Could it be because that deadline wasn't set, and therefore not visible?
 
    [% IF Param("timetrackinggroup") && bug.deadline %]


https://github.com/unee-t/bugzilla-customisation/blob/master/custom/bug/show-multiple.html.tmpl#L265

**Comment by franck-boullier** [comment]
"Or is my best tact for reproducing this issue is to dump the sql ?"
@kaihendry yes, I think this is your best option use a dump from the dev database (exclude the attach data though as it would be quite heavy)

**Comment by franck-boullier** [comment]
"Could it be because that deadline wasn't set, and therefore not visible?"
Good catch... It's worth testing that hypothesis...

**Comment by kaihendry** [comment]
Did you manage to test this out ?

**Comment by franck-boullier** [comment]
Yes just tested it and field is visible now
