### ISSUE TITLE
Search queries not working on clustered environments

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#36]
In the BZFE when we try to use a pre-configured search like this one (on the bottom of the BZEFE
![image](https://user-images.githubusercontent.com/31331637/36013962-3a28dea2-0da2-11e8-924c-d3663bf4ef9d.png)

Another example of a pre-saved query generates the following link:
https://dev.dashboard.unee-t.com/buglist.cgi?bug_status=__open__&component=Management%2520Company&list_id=509091&product=A_02-14_1%2520-%2520%2523263

This is incorrect as the query should be
https://dev.dashboard.unee-t.com/buglist.cgi?bug_status=__open__&component=Management%20Company&list_id=509093&product=A_02-14_1%20-%20%23263

The source of the issue is that the '%' seems to be escaped twice and converted into '%25'.
see:
- https://stackoverflow.com/questions/16084935/a-html-space-is-showing-as-2520-instead-of-20
A possible fix could be to tweak some of the Apache config: as explained here
- https://community.atlassian.com/t5/Confluence-questions/Why-confluence-link-URL-get-modified-with-25-sign/qaq-p/459280

The issue only happened in a clustered AWS environment and does NOT happen on a standard AWS EC2 installation.

**Comment by kaihendry** [comment]
I believe **Apache/2.4.18 (Ubuntu)** is rewriting this URL, not some AWS service.

<img src="https://s.natalian.org/2018-02-15/1518658365_2558x1406.png" alt="301 Moved Permanently">

Did you test locally with Apache & Docker compose?

https://github.com/unee-t/bugzilla/blob/master/bugzilla.conf probably needs a tweak.

**Comment by kaihendry** [comment]
I am trying to re-create this issue locally on http://localhost:8081

However when I create a saved search it looks like: <http://localhost:8081/buglist.cgi?cmdtype=runnamed&namedcmd=Sunny>

How come your **pre-saved query** example has a component parameter??

**Comment by franck-boullier** [comment]
@kaihendry How to replicate the issue:
Click on any of the links in the red circle
![image](https://user-images.githubusercontent.com/31331637/36238742-7f327930-123f-11e8-874f-fdece0682ee6.png)
This does NOT work in the DEV or PROD (on AWS cluster)
This DOES work on a local AWS ubuntu installation spun off with docker

**Comment by franck-boullier** [comment]
@kaihendry "How come your pre-saved query example has a component parameter??"
This is how the BZ guys have developed it...

**Comment by franck-boullier** [comment]
@kaihendry "Did you test locally with Apache & Docker compose?" yes in an EC2/ubuntu environment and the problem does NOT appear there (only in the DEV an PROD)

**Comment by kaihendry** [comment]
I see the problem. The link redirects to a http:// URL and then gets rewritten accidentally when redirected back to https://

<img src="https://s.natalian.org/2018-02-15/https-to-http.png">

**Comment by franck-boullier** [comment]
Ohhh!
Sneaky!
Good catch!

**Comment by franck-boullier** [comment]
Confirmed: tested in the Master in dev.dashboard and this works as intended

**Comment by franck-boullier** [comment]
Oops
Spoken too fast...
These links seem to work (no error thrown): 
- Open cases ... https://dev.dashboard.unee-t.com/buglist.cgi?f1=reporter&list_id=509180&o1=equals&resolution=---&v1=%2525user%2525 and https://dev.dashboard.unee-t.com/buglist.cgi?f1=reporter&list_id=509181&o1=equals&resolution=---&v1=%2525user%2525
- Requests addressed to me: https://dev.dashboard.unee-t.com/request.cgi?action=queue&requestee=franck.boullier%40lmbhousing.com&group=type&do_union=0
- Case changed in the last...: https://dev.dashboard.unee-t.com/buglist.cgi?chfieldfrom=24h&list_id=509177 and https://dev.dashboard.unee-t.com/buglist.cgi?chfieldfrom=7d&list_id=509178

These do not work: 
- Case reported in ...: https://dev.dashboard.unee-t.com/buglist.cgi?chfield=%255BBug%2520creation%255D&chfieldfrom=24h&list_id=509182 and https://dev.dashboard.unee-t.com/buglist.cgi?chfield=%255BBug%2520creation%255D&chfieldfrom=7d&list_id=509183

**Comment by kaihendry** [comment]
Maybe try in an incognito window?

Btw #bugzilla IRC told me I should set https://github.com/bugzilla/harmony/blob/master/httpd/httpd.conf#L71-L73 which I will try tomorrow if I get some time. Also they advised I should run mod_perl to better performance. Though I imagine the database in the bottle neck. Wonder how to get a request break down of where time is spent.

**Comment by franck-boullier** [comment]
@kaihendry "Maybe try in an incognito window?"
Tried that but the issue is still there...

**Comment by franck-boullier** [comment]
this works now I probably had some caching issue in my browser...
