### ISSUE TITLE
Feat - Links in the BZ email point to the BZFE - Should point to the MEFE

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#37]
When the BZ back end sends an email to a user notifying of a change in a case, the URL is the URL for the dashboard.

It should be the URL for the MEFE instead.

We need to customize the BZ email so that the URL is the URL for the MEFE and NOT the url for the BZFE.

Limit: in order for the URL to work, the user would have to be logged in to the MEFE as himself.
This is NOT a magic link!

This is acceptable in the MVP.

**Comment by nbiton** [comment]
I believe that a later stage we should disable the emails on BZ entirely, and triggered them directly from our Meteor stack.

**Comment by franck-boullier** [comment]
@nbiton "I believe that a later stage we should disable the emails on BZ entirely, and triggered them directly from our Meteor stack."
I totally agree with that but that's not possible for now: I'd prefer to have the MVP out ASAP rather than add some more delays and complexities.
So going for the kick fix...

**Comment by franck-boullier** [comment]
@nbiton what would be the url prefix that we'll need to append to the bug id so we can route a user directly to a case?
Will '[domain]/case/' work?

**Comment by franck-boullier** [comment]
@kaihendry, @sebdeckers, @nbiton I'm a bit stuck on that one...
Do you have any idea to handle this in a clever way?

The problem is that we have to deal with 2 environments in parallel:
1- BZFE which need the url prefix for the BZ installation (dashboard)
2- MEFE which needs the url prefix for the MEFE side (case)

Each time a case is modified, BZ has the ability to send an email to the users who have requested to be notified by email.
This is the default behavior for now for Unee-T.
This is not a problem yet as we only have users that are using the dashboard as their primary interface so the notification they receive includes a link to the dashboard.

This will change as soon as we start the pilot for MEFE only users: they have no access to the dashboard.
Giving them a link to the dashboard will create several issues and add confusion for the MEFE (case) only users -> I want to avoid that.

A quick and ugly fix will be to disable email notification for the MEFE only users but this means we are loosing and important functionality here: one of the reason users will get there is to get automated (push) notification when something changes on the case(s) they are involved in.

The obvious solution would be that the MEFE handles the email/notifications itself. We could then disable the BZ notification with no loss of functionalities.
BUT I have no idea how long this will take to get the MEFE to do that and we can't delay the pilot more than what we have already delayed it IMO...

Any suggestion on how we can solve that issue?

**Comment by nbiton** [comment]
Unfortunately, I don't believe there's an easy quick fix for this issue. I think the email notification should be disabled for MEFE users, and eventually implemented on MEFE.

**Comment by franck-boullier** [comment]
I agree and this is how we'll do it for now until further notice

**Comment by franck-boullier** [comment]
Long term solution is that the notifications will be generated by the MEFE.

For users who have no access to the dashboard, we will disable the email notifications.
