### ISSUE TITLE
Move MongoDB to mLab

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#4]
EFS is not available in the Singapore region.

https://twitter.com/nathankpeck/status/926317004641812486

@nbiton suggested mLab. Will open an account and switch to them ASAP for dev and production. 

Btw Mongo is lacking local mounts https://github.com/unee-t/bugzilla-customisation/blob/master/docker-compose.yml#L63

**Comment by sebdeckers** [comment]
Ohai, I was just looking at the same thing. 🧐 https://gitlab.com/http2/api/issues/7

Compose/mLab don't make sense to me anymore now that MongoDB Inc has its own service. At the same price, why would you go through a 3rd party for managed AWS hosting?

For Unee-T it really makes sense to host in US region given the business development plan to push the product over there. I believe AWS sponsors the fully managed free 512 MB MongoDB Atlas hosting in us-east-1 (and eu-central-1). Great for the initial dev/test setups.

**Comment by kaihendry** [comment]
I have the MongoDB Atlas account. Will create a dev/prod env in us-east-1.

**Comment by kaihendry** [comment]
We are now using MongoDB Atlas in us-east-1 under my account kai.hendry@unee-t.com

Let me know your emails and I will invite you to the account. Note the connection details are in `aws-env` and `aws-env.prod` atm.


https://s.natalian.org/2017-11-10/atlas.mp4
