### ISSUE TITLE
Consistent email address

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#40]
FROM_EMAIL is populated with:

```
$ aws --profile uneet-dev ssm get-parameters --names FROM_EMAIL --query Parameters[0].Value --output text
DEV Unee-T Case <dev.case@unee-t.com>
```

I noticed support.dashboard@unee-t.com on a [password reset email](https://s.natalian.org/2018-02-15/1518658092_1406x1406.png) & [bugzilla.dev@unee-t.com](https://github.com/unee-t/bugzilla/blob/master/bugzilla.conf#L2) elsewhere.

So can we agree that **all** staging email goes to dev.case@unee-t.com and that it is properly manned?

**Comment by franck-boullier** [comment]
sounds reasonable, I'll do the change in the dev.

1 of the issue is that today the email engine is in the BZFE.
Until we have a MVP for the MEFE, users can only interact via the BZFE.

Once we have a MVP for the MEFE, we will:
- change the maintainer email address to xxx.case@unee-t.com
- change the url prefix in the emails sent from the BZ engine from xxx.dashboard.xxx to xxx.case.xxx so the links in the emails sent by the BZ engine points to the MEFE instead (see issue #37

**Comment by franck-boullier** [comment]
"I noticed support.dashboard@unee-t.com on a password reset email & bugzilla.dev@unee-t.com elsewhere."
More details on my previous reply:
email address 'support.dashboard@unee-t.com' is a parameter that can be changed in the BZFE (email for the installation maintainer)

@kaihendry 1 complexity is that the login mechanism between the BZFE and the MEFE are linked but the password reset procedure are not.
It is possible today to reset the BZEFE password and this is done in the BZFE interface, in this scneario it makes sense that the email sender is referring to the BZFE so we might have to have 2 email addresses configured in the BZFE

**Comment by kaihendry** [comment]
```
[hendry@t480s params]$ grep mailfrom *
demo-params.json:   "mailfrom" : "demo.case@unee-t.com",
dev-params.json:   "mailfrom" : "dev.case@unee-t.com",
local-params.json:   "mailfrom" : "dev.case@unee-t.com",
prod-params.json:   "mailfrom" : "case@unee-t.com",
```

Can we agree on this structure:

```
[hendry@t480s tmp]$ cat foo.sh
for STAGE in dev demo prod
do
        echo STAGE: $STAGE
        test $STAGE == "prod" && echo https://dashboard.unee-t.com || echo https://$STAGE.dashboard.unee-t.com
        test $STAGE == "prod" && echo https://case.unee-t.com || echo https://$STAGE.case.unee-t.com
        test $STAGE == "prod" && echo case@unee-t.com || echo $STAGE.case@unee-t.com
        echo ""
done
[hendry@t480s tmp]$ bash foo.sh
STAGE: dev
https://dev.dashboard.unee-t.com
https://dev.case.unee-t.com
dev.case@unee-t.com

STAGE: demo
https://demo.dashboard.unee-t.com
https://demo.case.unee-t.com
demo.case@unee-t.com

STAGE: prod
https://dashboard.unee-t.com
https://case.unee-t.com
case@unee-t.com
```

For local development, we assume the **dev** stage?

**Comment by franck-boullier** [comment]
Yes

**Comment by kaihendry** [comment]
This is the current naming style:

```
STAGE: dev
https://dev.media.unee-t.com
s3://dev-media-unee-t
auroradb.dev.unee-t.com
https://case.dev.unee-t.com
https://dashboard.dev.unee-t.com
case.dev@unee-t.com

STAGE: demo
https://demo.media.unee-t.com
s3://demo-media-unee-t
auroradb.demo.unee-t.com
https://case.demo.unee-t.com
https://dashboard.demo.unee-t.com
case.demo@unee-t.com

STAGE: prod
https://media.unee-t.com
s3://media-unee-t
auroradb.unee-t.com
https://case.unee-t.com
https://dashboard.unee-t.com
case@unee-t.com

```
