### ISSUE TITLE
Debug 502/503 errors on https://dashboard.unee-t.com/ (production 1924-5899-3663)

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#41]
Related performance issue https://github.com/unee-t/bugzilla/issues/8

https://ap-southeast-1.console.aws.amazon.com/ecs/home?region=ap-southeast-1#/clusters/master/services/ecscompose-service-bugzilla/events does suggest there is an issue.

<img src="https://s.natalian.org/2018-03-01/1519869607_2558x1406.png" alt="Request time outs">

Can't see the same behaviour on [staging 8126-4485-3088](https://ap-southeast-1.console.aws.amazon.com/ecs/home?region=ap-southeast-1#/clusters/master/services/ecscompose-service-bugzilla/events). So this is going to be fun.

There are no clues in the bugzilla logs. https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logStream:group=bugzilla;streamFilter=typeLogStreamPrefix

On Mozilla IRC, \#bugzilla advised for tracing:
```

22:55 <@dylan> hendry: if you want to do some profiling -- after you've got mod_perl turned on, you can copy:  https://github.com/mozilla-bteam/bmo/blob/master
/mod_perl.pl#L27-L33, https://github.com/mozilla-bteam/bmo/blob/master/mod_perl.pl#L151-L157, https://github.com/mozilla-bteam/bmo/blob/master/mod_perl.pl#L161
-L164
22:55 <@dylan> this will produce nytprofile files in the data/ directory
22:56 <@dylan> you can turn them into pretty readable reports with nytprofhtml command. you'll need the package Devel::NYTProf for that however.
```

**Comment by franck-boullier** [comment]
I'll close that for now.
Will reopen if I get info from users that the issue resurfaces

**Comment by franck-boullier** [comment]
Usser report that the issue reappears again

**Comment by franck-boullier** [comment]
@kaihendry unee-T dashbord down again
Issue started around 15h15 and is still going intermittently as per users

**Comment by kaihendry** [comment]
I see something that correlates <img src="https://s.natalian.org/2018-03-02/1519976926_2558x1406.png">

**Comment by franck-boullier** [comment]
error again at 15h55

**Comment by franck-boullier** [comment]
error still there at 16h03

**Comment by franck-boullier** [comment]
![bad_gateway_15h55](https://user-images.githubusercontent.com/31331637/36889105-6cd4cfae-1e33-11e8-86fe-f55eff32934f.png)

**Comment by franck-boullier** [comment]
user confirm that the issue is intermittent and that it comes and go, sometimes it works, other it doesn't...

**Comment by franck-boullier** [comment]
issue appears again at 16h08

**Comment by kaihendry** [comment]
We are hitting a memory limit. Trying to fix it. https://twitter.com/kaihendry/status/969482548949626881

**Comment by franck-boullier** [comment]
OK @kaihendry thanks for the update

**Comment by kaihendry** [comment]
A change I've made in staging appears to work, so I'll deploy to production: https://s.natalian.org/2018-03-02/1519978222_2558x1406.png

**Comment by franck-boullier** [comment]
@kaihendry, Can this be part of the explanation: http://bugzilla.readthedocs.io/en/latest/installing/apache.html#apache-with-mod-perl

---

mod_perl support in Bugzilla can take up a HUGE amount of RAM - easily 30MB per httpd child. The more RAM you can get, the better. mod_perl is basically trading RAM for speed. At least 2GB total system RAM is recommended for running Bugzilla under mod_perl.

---

**Comment by kaihendry** [comment]
I'm aware. We have 4GB on the t2, but the container is being artificially limited by default in ECS.

**Comment by franck-boullier** [comment]
@kaihendry not sure if relevant but this too:

---

Warning

You should also ensure that you have disabled KeepAlive support in your Apache install when utilizing Bugzilla under mod_perl or you may suffer a performance penalty. 

---

**Comment by franck-boullier** [comment]
"I'm aware. We have 4GB on the t2, but the container is being artificially limited by default in ECS."
OK

**Comment by kaihendry** [comment]
I'm tracking 5xx errors here in the production account btw: https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#alarm:alarmFilter=ANY;name=track5xx

If you wanted to, you could add your email to the SNS topic.

<img src="https://s.natalian.org/2018-03-02/1519980224_2558x1406.png" alt="5xx tracking">

**Comment by kaihendry** [comment]
I'm somewhat confident this change will fix it. https://github.com/unee-t/bugzilla-customisation/commit/e9c82bc9f7136bace0a422c704de356cffa1ba4a

I've fixed it manually in production, but next deployment (i.e. tag) should make this policy.

**Comment by Nath2018LMB** [comment]
We experienced this new error yesterday, 05 March 2017.

![e0cb58c9-4b12-490f-8d46-6f67e9084498](https://user-images.githubusercontent.com/36984235/37012340-286e8b80-212f-11e8-8df2-40d14dd8695f.JPG)

**Comment by franck-boullier** [comment]
@Nath2018LMB I'm creating a new issue for that as I'm not sure these are related...

**Comment by kaihendry** [comment]
New issue was: https://github.com/unee-t/bugzilla-customisation/issues/42

I'm tracking issues in https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#dashboards:name=ECS

Hopefully this issue is solved.
