### ISSUE TITLE
Document administrator user/pass

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#48]
If something goes wrong with Bugzilla, I don't have access to the administrator user name or pass word to debug settings. I could go straight into the database, but it's easier to look at */admin.cgi* in light of the params.json.

Perhaps:

* BZFE_ADMIN_USER
* BZFE_ADMIN_PASS

**Comment by franck-boullier** [comment]
Done for the DEMO environment

**Comment by kaihendry** [comment]
Is this the same for https://demo.case.unee-t.com/ ?

Ideally could have dev too.

**Comment by kaihendry** [comment]
Same issue as https://github.com/unee-t/frontend/issues/47 really. Always getting frustrated here. :sweat_smile:

**Comment by franck-boullier** [comment]
Done for the DEV environment

**Comment by franck-boullier** [comment]
@kaihendry "Is this the same for https://demo.case.unee-t.com/ ?"
There is no concept of an administrator for the MEFE: all permissions are managed in the BZFE today
