### ISSUE TITLE
demo environment is not formated properly

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#49]
url: https://demo.dashboard.unee-t.com/admin.cgi

![image](https://user-images.githubusercontent.com/31331637/37695963-264b4010-2d0e-11e8-87a7-eb9a59ea53a0.png)

I seem to recall that we had a similar problem in the past...

**Comment by kaihendry** [comment]
Yes, I must add a script that checks for the sticky bit across environs. I have some checks here already: https://github.com/unee-t/bugzilla-customisation/tree/master/ecs-check

**Comment by kaihendry** [comment]
Btw, I've fixed the stickiness value of the demo's bugzilla target. Just trying to develop a script to check it.
