### ISSUE TITLE
Move aws-env* to parameter store

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#5]
Idea is that if AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY is correctly set, with the right permissions/role whatever, all the keys values will be set via `aws ssm get-parameter`.

**Comment by franck-boullier** [comment]
Once again I'm a bit lost and I'll more information and context on where/when/how this should be done.
I'm trying to configure the dashboard in the prod environment and I'm scratching my head on how I can efficiently convert this from what looks like a vanilla BZ installation into a the latest version of the BZFE.

The first issue I'm running into is I don't know where to find the password for the initial user created in (contributor@example.com). I could work around that probably but this is just to illustrate how lost I fell right now...
Apologies for what might appear to be a very dumb  question...

**Comment by kaihendry** [comment]
I think your query is about SQL, and not about the secrets in the environment, right?



The production SQL was primed IIUC by checksetup.pl.

I assumed you would basically overwrite the SQL in the production database at this point. I.e. not use the Web interface to setup anything regarding the database.

**Comment by franck-boullier** [comment]
I could do that
That was my initial impulse actually but I just wanted to make sure that this was the right thing to do...
I was actually wondering why you did not use the sql dump from the Bugzilla configuration folder when you re-built the production environment...

**Comment by franck-boullier** [comment]
This also leads to a related question: "if the DB is a vanilla DB, which other customization have been omitted there? Skins? Custom?"

**Comment by franck-boullier** [comment]
"I assumed you would basically overwrite the SQL in the production database at this point."
just for the records, I just did that right now...

**Comment by kaihendry** [comment]
The running production as I left it over the weekend basically only has the initial localconfig/params.json. Nothing from https://github.com/unee-t/bugzilla-customisation/tree/master/sql.

From there I think skins and custom are setup.

**Comment by franck-boullier** [comment]
OK thanks for the clarification.
I'll do the params.json manually in the back end (much faster for now) and then we'll be able to lift the params.json file once I understand where I need to log in to execute the command
`docker cp customisation_bugzilla_1:/opt/bugzilla-5.0.3/data/params.json /tmp/params.json`

**Comment by franck-boullier** [comment]
<img width="736" alt="no_such_container_error" src="https://user-images.githubusercontent.com/31331637/32430651-24d309ec-c30b-11e7-990c-0ea02da3e1d5.png">
Error message in my "local" ubuntu dev environment
@kaihendry any suggestions?

**Comment by franck-boullier** [comment]
prod environment configured BEFORE migration.
parameters have been modified. The file params.json should be OK (I still need to understand how I can copy it).
email tested and seem to work as intended.
Next step will be to migrate the LMB users and cases from the LMB internal tool into Unee-T

**Comment by kaihendry** [comment]
What's your `docker ps` output?

**Comment by franck-boullier** [comment]
<img width="810" alt="docker ps output" src="https://user-images.githubusercontent.com/31331637/32431327-0ff7ac5a-c30e-11e7-9188-9a8f07906d90.png">

**Comment by kaihendry** [comment]
Aren't you missing the `make up` step to get your Docker containers up and running?

**Comment by franck-boullier** [comment]
I do miss it...
for some reason I took that installation down and forgot to build it up again :blush:

Still have the same error though
<img width="784" alt="docker ps output_after_make_up" src="https://user-images.githubusercontent.com/31331637/32431690-6159c960-c30f-11e7-811b-619cb310c183.png">

**Comment by kaihendry** [comment]
Docker has inconsistent naming between versions. I can see your running container is called "bugzillacustomisation_bugzilla_1", so you need to adjust the copy command accordingly.

**Comment by franck-boullier** [comment]
cool that did it thanks!

**Comment by kaihendry** [comment]
This is done https://s.natalian.org/2017-11-10/1510284612_2558x1406.png
