### ISSUE TITLE
Publish events to AWS SNS from Bugzilla

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#59]
Unee-T will sponsor this integration, which would probably be accomplished like so `Paws->service('SNS')->Publish(Message => $jsonPayload, TopicArn => '...');`. Please contact me for a AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY.

This will hopefully enable us to fix:
* https://github.com/unee-t/frontend/issues/186
* https://github.com/unee-t/frontend/issues/185

But not https://github.com/unee-t/frontend/issues/191 (which would probably have to come from the Frontend)

**Comment by kaihendry** [comment]
Hopefully these events readily translate to actions like "A new case is created" as seen here:
![image](https://user-images.githubusercontent.com/765871/38843908-c09304ee-4223-11e8-9d28-ef519882b130.png)

This approach I'm assuming is easier to work then than the alternative approach (of achieving the same goal) of [eventing on db changes](https://github.com/unee-t/frontend/issues/186#issuecomment-381517805)..

**Comment by franck-boullier** [comment]
"This approach I'm assuming is easier to work then than the alternative approach (of achieving the same goal) of eventing on db changes.."
@kaihendry I disagree as this approach is only valid for the BZFE the alternative approach will work regardless of where the change has been initiated from the MEFE or from the BZFE.
The other approach is also a lot less BZ dependant and will be much easier to migrate/reuse in future upgrades and iterations.

**Comment by franck-boullier** [comment]
Preferred solution as of now is to go serverless if and when possible.
Solution we are working on for Unee-T v3.x+ is to leverage AWS functionalities:
- Host the BZ database on Aurora
- Create custom table and procedures in the BZ database to record changes in a case/bug (new bug, new bug activity, new message)
- Create a lambda function to generate the notification
- Use AWS lambda and Aurora integration to send notification each time an update is done to a case.

Feel free to re-open this issue if there is a better/more efficient alternative.

**Comment by kaihendry** [comment]
Ok, we've opted to go for a pure DB driven approach here: https://github.com/unee-t/bz-database/issues/36
