### ISSUE TITLE
PROCEDURE bugzilla.table_to_list_dummy_user_by_environment does not exist

### ISSUE THREAD

**Issue by kaihendry** [unee-t/bugzilla-customisation#65]
When developing locally, `demo.sql.gz` seems to be missing some schema. Therefore https://github.com/unee-t/invite/tree/master/sql fails to run and fails to invoke an invitation.

```
by_environment does not exist * nFKobGdSNewju7DP7 Error 1305: PROCEDURE bugzilla.table_to_list_dummy_user_by_environment does not exist * QxdJo7oebbACkqhRm Err
or 1305: PROCEDURE bugzilla.table_to_list_dummy_user_by_environment does not exist * p43fdzfRG2PsD3KhK Error 1305: PROCEDURE bugzilla.table_to_list_dummy_user_
by_environment does not exist * xSnMusxGBE67XnDFT Error 1305: PROCEDURE bugzilla.table...]
I20180614-13:51:51.665(8)?   response:
I20180614-13:51:51.668(8)?    { statusCode: 500,
I20180614-13:51:51.669(8)?      content: '6 errors occurred:\n\n* HjBiNS9Ravjs9w7TH Error 1305: PROCEDURE bugzilla.table_to_list_dummy_user_by_environment does
 not exist\n* nFKobGdSNewju7DP7 Error 1305: PROCEDURE bugzilla.table_to_list_dummy_user_by_environment does not exist\n* QxdJo7oebbACkqhRm Error 1305: PROCEDUR
E bugzilla.table_to_list_dummy_user_by_environment does not exist\n* p43fdzfRG2PsD3KhK Error 1305: PROCEDURE bugzilla.table_to_list_dummy_user_by_environment d
oes not exist\n* xSnMusxGBE67XnDFT Error 1305: PROCEDURE bugzilla.table_to_list_dummy_user_by_environment does not exist\n* BedKAbRt5osMYxawY Error 1305: PROCE
DURE bugzilla.table_to_list_dummy_user_by_environment does not exist\n',
I20180614-13:51:51.672(8)?      headers:
I20180614-13:51:51.673(8)?       { 'content-type': 'text/plain; charset=utf-8',
I20180614-13:51:51.674(8)?         'x-content-type-options': 'nosniff',
I20180614-13:51:51.675(8)?         'x-robots-tag': 'none',
I20180614-13:51:51.676(8)?         date: 'Thu, 14 Jun 2018 05:51:51 GMT',
I20180614-13:51:51.677(8)?         'content-length': '656',
I20180614-13:51:51.678(8)?         connection: 'close' },
I20180614-13:51:51.679(8)?      data: null } }
```

**Comment by franck-boullier** [comment]
Did you run the script to create the demo environment?
https://github.com/unee-t/bz-database/blob/master/demo-test%20environment/create_demo_environment_clean.sql

I don't want to include that in the seed script for fear of messing things up in the DEV or PRO (but maybe I should)...

**Comment by franck-boullier** [comment]
OK looking at this issue with fresh eyes: this seems like you are running an outdated version of the BZ database schema...
Can you check which version you are using?

**Comment by franck-boullier** [comment]
We need to update `demo.sql.gz` in https://github.com/unee-t/bugzilla-customisation/tree/master/sql

# How it is done:
- take the latest version of the file `unee-t_BZFE_vx.y_clean.sql` in the repo https://github.com/unee-t/bz-database/tree/master/db%20snapshots
- compress this file as a gz archive
- rename the .gz archive to `demo.sql.gz`
- replace the file `demo.sql.gz` in the repo https://github.com/unee-t/bugzilla-customisation/tree/master/sql

@kaihendry I'm guessing this should be relatively straight forward to automate but I must confess that I have 0 clue on how this could be done...

**Comment by kaihendry** [comment]
You shouldn't version the name of the file, since we are using version control (git). 

Just use **unee-t_BZFE_clean.sql** and then addressing it becomes sane.
