### ISSUE TITLE
No products are accessible to users; users' admin roles have been revoked

### ISSUE THREAD

**Issue by nbiton** [unee-t/bugzilla-customisation#73]
The change was observed this morning. The cause for this change is yet unknown

**Comment by franck-boullier** [comment]
Check the BZ database:
- Products are still there in the `products` table there are 637 products

**Comment by nbiton** [comment]
Things that we have noticed so far:
* Users can still access their cases.
* Even the administrator.dev user doesn't appear as admin anymore.

**Comment by franck-boullier** [comment]
Check in the BZ database:
- Users are still there in the `profiles` table (there are 997 profiles)

**Comment by franck-boullier** [comment]
There are 20962 groups in the BZ db
User administrator.dev is NOT a member of the group of users for admin.

The table `user_group_map` is empty 
---> this is abnormal 
---> this is at least one of the reasons why we are experiencing the reporting problem
---> we need to understand why it happened

**Comment by franck-boullier** [comment]
@kaihendry do we have a log somewhere to track the changes done to a specific table? That could help us pinpoint the event that cause this table to be nuked...

**Comment by franck-boullier** [comment]
An idea:
@nbiton maybe this is related to the tests in the BZ master database to add users to a role in a given unit...

There is on step in one of the many scripts that are fired to invite a user to a unit where we need to empty the table `user_group_map` and then immediately re-populate it.

If for some reason the process is interrupted at the wrong time, then the `user_group_map` might be emptied but not re-populated as it should ---> that might explain why this table is now empty 🤔

**Comment by nbiton** [comment]
I wasn't aware of this step, but it shouldn't be very much unlike any other invitation we already had for a very long time

**Comment by franck-boullier** [comment]
> I wasn't aware of this step

The more I think about this, the more I feel that this might be the root cause of the issue...
We need 
- to try to replicate the things you've done over the past few days to test the invitation mechanism an see if we can replicate that error (table `user_group_map`  is emptied but nor properly re-populated)
- make the script that updated the user permissions more robust to make sure that is the table `user_group_map` is empty then we handle that better (I have a few ideas...)

**Comment by nbiton** [comment]
> to try to replicate the things you've done over the past few days to test the invitation mechanism an see if we can replicate that error (table user_group_map is emptied but nor properly re-populated)

@franck-boullier I have been working on it locally and just deployed my code. Haven't tested the actual function in a way that triggers the invite lambda on dev.

**Comment by franck-boullier** [comment]
@nbiton OK I guess we're back to combing the log to see if we can understand what triggered that...

I still plan to improve the procedure to update the user group membership... See https://github.com/unee-t/bz-database/issues/88 for more details

**Comment by kaihendry** [comment]
To track every SQL request, I need to enable the "BINLOG", which it isn't by default. Should I enable it with 24hr retention on dev and prod DBs?

I did a point in time restore to 00:00 of today IIUC. This is sadly a tedious process that took hours.

```
[hendry@t480s db]$  mysql -h rollback.c5eg6u2xj9yy.ap-southeast-1.rds.amazonaws.com -P 3306 -u root --password=SAME mysql
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 451
Server version: 5.7.12 MySQL Community Server (GPL)

Copyright (c) 2009-2018 Percona LLC and/or its affiliates
Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select * from user_group_map;
ERROR 1146 (42S02): Table 'mysql.user_group_map' doesn't exist
mysql> use bugzilla
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from user_group_map;
Empty set (0.03 sec)

```

And it would appear **user_group_map** is empty?

**Comment by kaihendry** [comment]
Ah! I found 24903 rows in rollbackfurther.c5eg6u2xj9yy.ap-southeast-1.rds.amazonaws.com

How do we proceed from here?

**Comment by franck-boullier** [comment]
> To track every SQL request, I need to enable the "BINLOG", which it isn't by default. Should I enable it with 24hr retention on dev and prod DBs?

Yes I think we should.
Is 24 hours enough though? What happens if something happens during the WE?

**Comment by kaihendry** [comment]
I've updated auroradb.dev.unee-t.com DNS to point to rollbackfurther-cluster.cluster-ro-c5eg6u2xj9yy.ap-southeast-1.rds.amazonaws.com & the Postman check works now.

<img src="https://s.natalian.org/2018-10-18/1539839399_2558x1406.png">
