### ISSUE TITLE
Variables that are environment specific - API key for the Meteor users (ex: Administrator)

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/bugzilla-customisation#9]
The MEFE needs to communicate with the BZFE.
In order to do this, we use the BZ API mechanism.

Each user for each environment needs to have an API key that is properly configured in the MEFE and the BZFE to make sure that the 2 system can communicate.

The first user that we need to worry about it the Admin user (user id 1 in the BZFE).

As of today, the API key for each users are recorded in the table 'user_api_key' in the BZ installation.

We need to make sure that each time we deploy in a new environment (demo, dev, prod, etc...) the correct API is used for the relevant user.

This issue tracks how we will do that.

Context:
The current SQL primer in the Docker container only creates 1 admin user.
This is not a problem for now as we know that we need to run a specific SQL script to create demo users for each environment. The script to create demo user is currently available in https://github.com/unee-t/bz-database/tree/master/demo-test%20environment.
We DO NOT want to store the Administrator API key there for any sensitive (i.e non local) environment as this is a public repo.
The only API key that should be visible there is the generic API key that a dev will use in a "local" installation.

**Comment by kaihendry** [comment]
When I deploy, I test the Meteor front end works by creating a new user. If it doesn't, it's typically due to the BUGZILLA_ADMIN_KEY not matching with Bugzilla.

If it doesn't, I regenerate an API key in Bugzilla and update BUGZILLA_ADMIN_KEY in AWS parameter store (aka ssm) and re-deploy Meteor front end.

**Comment by franck-boullier** [comment]
@kaihendry that's clever but why not generate a totally new API key each time we do a deployment then? This would have the same result with the added benefit of having a different API key for each envo

**Comment by kaihendry** [comment]
Generating an API key with Bugzilla is manual. It should be static once it's there. I don't see why it should change.

**Comment by franck-boullier** [comment]
Unless I am missing something there the API key for the admin user for the DEV and PROD environment should be secret or else anyone with this API key could wreak havoc in these envos.

If we have dockers using the same API for the admin user each time an envo is deployed then we need an additional step in the DEV and PROD: change the default API key to something that is not public.

Generating random API key each time we deploy a new envo should eliminate this step right?

**Comment by kaihendry** [comment]
The BUGZILLA_ADMIN_KEY is not public. It's a secret, maintained in AWS's secure store that's derived by the environment setting step:
* https://github.com/unee-t/bugzilla-customisation/blob/master/aws-env.prod
* https://github.com/unee-t/bugzilla-customisation/blob/master/aws-env

**Comment by franck-boullier** [comment]
The BUGZILLA_ADMIN_KEY is visible in the database for each user in the table 'user_api_key' too.
Anyone with access to the database can see all these keys.

**Comment by kaihendry** [comment]
I thought there there was *one* global key set by the administrator. 

I assumed this key would be hidden from users. If users are expected to work on their individual keys then I think this will get messy indeed.

**Comment by franck-boullier** [comment]
API keys are set individually by/for each BZ user. This is how BZ knows which permissions and privileges are granted to the user that is making an API call.
A BZ user can have several API keys too.
Administrator is a BZ user and behave as any other users as far as API keys are concerned.

**Comment by kaihendry** [comment]
Oh, I didn't realise it was like that. I guess in that case Meteor needs to generate and store the API key itself? cc @nbiton 

For the purposes of a prototype I was hoping we could get away with an administrator account and then perhaps move away from Bugzilla. Fine grained permissions surely aren't required for a MVP?

**Comment by nbiton** [comment]
We need to see how it could be done via the REST API

**Comment by franck-boullier** [comment]
@kaihendry "Fine grained permissions surely aren't required for a MVP?"

Fine grained permission is an absolute must have for the MVP unfortunately

**Comment by franck-boullier** [comment]
@nbiton "We need to see how it could be done via the REST API"
It looks like a chicken and egg story for the administrator user: you need an API key so you can use the REST API
For the other users it might be possible to use the REST API and the API key for the administrator to create the API key for the newly created BZ user (not too sure about that).

This should not be critical for the MVP though as all the users will be first created manually in both systems so we can work around that somehow...

But making sure that the API key for the Administrator user is correctly protected and not unintentionally exposed to the world is a must have for the MVP though.

**Comment by nbiton** [comment]
I think there's no way going around the Admin key being in the SQL database, as that's the only source of "truth". If anyone has direct access to the DB, he could manipualte anything anyway. On the MEFE side, it is stored as an env variable which is protected by the AWS creds.
The part about generating API keys for each individual user to be used for the requests sent by MEFE is what I was referring to when I said we need to check how it can be done via the API. Currently, we're storing only the user creds and API tokens on the MEFE side for making the requests.

**Comment by franck-boullier** [comment]
"I think there's no way going around the Admin key being in the SQL database"
I totally agree with that and this is why it is important that this key is not the same across every installation. If this is the case then you can just lift the API key for the administrator from one of the dev environment and use it to access any other envo as adminitrator (inculding the production) using this API key.

**Comment by nbiton** [comment]
As far as I can tell, BZ is generating a unique key on every new installation, so I don't think this would be an issue

**Comment by franck-boullier** [comment]
"As far as I can tell, BZ is generating a unique key on every new installation"
Unfortunately and as far as I understand it this is NOT the case for API Keys for BZ users.
API key have to be generated by the BZ user AFTER the user is created. 
This is done in the BZ "preferences" menu in the BZ interface.

**Comment by kaihendry** [comment]
Just testing this morning on d7577e9, where my demo.sql.gz doesn't set an API at all.

When trying to generate one, I get a "no sender" error.

<img src=https://s.natalian.org/2017-12-15/1513303015_2558x702.png alt="no sender">

Working around the issue by adjusting Email parameters to "nomail"

**Comment by franck-boullier** [comment]
"Just testing this morning on d7577e9, where my demo.sql.gz doesn't set an API at all."
This is correct. The current demo.sql.gz does not set the user_api_key for the administrator.

The reason I did not set this in the demo.sql.gz file is because the user API key for the administrator should be environment specific.

The "no sender" error is due to a missing parameter in your environment.
You need to configure the maintainer email address and the mail delivery method for this to work.

Adjusting Email parameters to "nomail" is not a workaround but a valid solution if you choose to leave the email configuration parameters blank.

Email parameters can be configured in adminstration >> parameters >> emails.

**Comment by kaihendry** [comment]
How is "no sender" configured and what should it be for local env?

**Comment by franck-boullier** [comment]
it's configured in the [local-params.json](https://github.com/unee-t/bugzilla-customisation/blob/master/params/local-params.json) file
For local env
line 51 should read 
   "mail_delivery_method" : "Test",

**Comment by kaihendry** [comment]
Is this bug done? What's outstanding? The logic to handle more granular API keys?

**Comment by kaihendry** [comment]
> The reason I did not set this in the demo.sql.gz file is because the user API key for the administrator should be environment specific.

IIUC _demo.sql.gz_ is only used for local development. I.e. to get Frontend developers up and running as quickly as possible. Currently the manual steps of generating the administratrator@example.com API key and setting [**BUGZILLA_ADMIN_KEY**](https://github.com/unee-t/frontend/blob/master/.env.sample) costs precious time and creates barriers to entry.

Could there please be a default Administrator API key set in _demo.sql.gz_

**Comment by kaihendry** [comment]
Environments variables are described in AWS Systems Manager Parameter Store.


```
#!/bin/bash

if test "$2"
then
        echo aws --profile $1 ssm get-parameters --names $2 --with-decryption --query Parameters[0].Value --output text
        aws --profile $1 ssm get-parameters --names $2 --with-decryption --query Parameters[0].Value --output text
else
        aws --profile ${1:-uneet-dev} ssm describe-parameters
fi

```
